version: "3.9"

services:
  hotdeal-scrapper:
    hostname: hotdeal-scrapper
    container_name: hotdeal-scrapper
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    env_file:
      - .env
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - bot

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - bot

  loki:
    image: grafana/loki:latest
    container_name: "loki"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - bot

  promtail:
    image: grafana/promtail:latest
    container_name: "promtail"
    volumes:
      - ./grafana/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    networks:
      - bot

networks:
  bot:
